// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://flwmnhkmskullbcngkgr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsd21uaGttc2t1bGxiY25na2dyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4MDkwMzksImV4cCI6MjA3MTM4NTAzOX0.hIChR3OehcWvr4pndMic_cl9T3Oc_KI2lB0S_0mLgDE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});